online_shop/accountapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view


app_name = 'accountapp'
urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login-view'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout-view'),
    path('register/', views.RegisterView.as_view(), name='register-view'),
    path('password/change/', views.PassChangeView.as_view(template_name='passChange.html'), name='pass-change'),
    path('password/change/done/',
         auth_view.PasswordChangeDoneView.as_view(template_name='passChaneDone.html'),
         name='pass-change-done'),

    path("password_reset/", views.PassResetView.as_view(template_name='passReset.html'), name="password_reset"),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(template_name='passResetSent.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PassResetConfirmView.as_view(template_name='passResetConf.html'),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(template_name='passResetDone.html'),
        name="password_reset_complete",
    ),

]

online_shop/api/urls.py
from django.urls import path, include
from .views import *
urlpatterns = [
    path('laptop/list/', LaptopListAPIView.as_view()),
    path('mobile/list/', MobileListAPIView.as_view()),
    path('product/detail/<int:pk>/', ProductRetrieveUpdateDeleteAPIView.as_view()),

    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),

    path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/',
         PassResetConfirmView.as_view(),
         name='password_reset_confirm')
]

online_shop/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from accountapp import views
from api.views import PassResetConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store_app.urls')),
    path('api/', include('api.urls')),
    path('accountapp/', include('accountapp.urls')),




]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/store_app/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'store_app'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

    path('laptops/', views.LaptopListView.as_view(), name='laptop-view'),
    path('search/', views.SearchView.as_view(), name='search-view'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='detail-view'),
    path('purchases/', views.ShoppingListView.as_view(), name='purchases-view'),
    path('m/<int:pk>/', views.shopping_basket_minus, name='m-view'),
    path('p/<int:pk>/', views.shopping_basket_plus, name='p-view'),
    path('factor/', views.factor_view, name='factor'),
    path('bank/', TemplateView.as_view(template_name='store_app/bank.html'), name='bank'),
    path('uns/', TemplateView.as_view(template_name='store_app/unsuccess-result.html'), name='unsuccess'),
    path('success/', views.result_success_view, name='success'),
    path('mobiles/', views.MobileListView.as_view(), name='mobile-view'),
]

online_shop/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
  <title>Bootstrap 5 Website Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
    {% block head %}

    {% endblock %}
</head>
<body>

    <!-- header -->
    <div class="p-5 bg-primary text-white text-center">
      <h1 style="font-family:Times New Roman;">Mamali Online Shop</h1>
    </div>
    <!-- end header -->


    <!-- Navbar -->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
          <div class="container-fluid">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store_app:laptop-view' %}">Laptop</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store_app:mobile-view' %}">Mobile</a>
                    </li>
                    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store_app:purchases-view' %}">Shopping basket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accountapp:pass-change' %}">change password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accountapp:logout-view' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Welcome, {{ user.username }}</a>
                        </li>
                    {% else %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accountapp:register-view' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accountapp:login-view' %}">Login</a>
                        </li>
                    {% endif %}


                </ul>
          <form method="get" action="{% url 'store_app:search-view' %}" class="d-flex">
            <input class="form-control me-2" type="text" name="search" placeholder="Search">
            <button class="btn btn-primary" type="submit">Search</button>
          </form>
          </div>
    </nav>
    <!-- end navbar -->

    <div class="container mt-5">
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>
    </div>

    <!-- footer -->
    <div class="mt-5 p-4 bg-dark text-white text-center">
      <p>Footer</p>
    </div>

</body>
</html>

online_shop/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="col-sm-4">
          <h2>Welcome to</h2>
          <h5>Mamali online shop</h5>
          <div class="fakeimg"><img width="100%" height="100%" src="{% static 'img/02.jpeg' %}"></div>
          <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
          <h3 class="mt-4">Some Links</h3>
          <p>Lorem ipsum dolor sit ame.</p>
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store_app:laptop-view' %}">Laptop</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store_app:mobile-view' %}">Mobile</a>
            </li>

          </ul>
          <hr class="d-sm-none">
        </div>
        <div class="col-sm-8">
          <h2>TITLE HEADING</h2>
          <h5>Title description, Dec 7, 2020</h5>
          <div class="fakeimg"><img width="100%" height="100%" src="{% static 'img/04.png' %}"> </div>
          <p>Some text..</p>
          <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>

          <h2 class="mt-5">TITLE HEADING</h2>
          <h5>Title description, Sep 2, 2020</h5>
          <div class="fakeimg"><img width="100%" height="100%" src="{% static 'img/03.jpg' %}"></div>
          <p>Some text..</p>
          <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
        </div>

{% endblock %}

online_shop/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <p><a href="{% url 'accountapp:password_reset' %}">Forget Password</a> </p>
        <input type="submit" class="btn btn-primary" value="Login">
    </form>

{% endblock %}

online_shop/templates/passChaneDone.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <h2> Your Password changed successfully.</h2>

{% endblock %}

online_shop/templates/passChange.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

{% endblock %}

online_shop/templates/passReset.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>

{% endblock %}

online_shop/templates/passResetConf.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>

{% endblock %}

online_shop/templates/passResetDone.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <h2> Your Password changed successfully.</h2>
    <p> Go to <a href="{% url 'accountapp:login-view' %}">login</a>  page.</p>

{% endblock %}

online_shop/templates/passResetEmail.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accountapp:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

online_shop/templates/passResetSent.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <h2> Reset link has been sent to your email. </h2>

{% endblock %}