online_shop/accountapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view


app_name = 'accountapp'
urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login-view'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout-view'),
    path('register/', views.RegisterView.as_view(), name='register-view'),
    path('password/change/', views.PassChangeView.as_view(template_name='passChange.html'), name='pass-change'),
    path('password/change/done/',
         auth_view.PasswordChangeDoneView.as_view(template_name='passChaneDone.html'),
         name='pass-change-done'),

    path("password_reset/", views.PassResetView.as_view(template_name='passReset.html'), name="password_reset"),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(template_name='passResetSent.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PassResetConfirmView.as_view(template_name='passResetConf.html'),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(template_name='passResetDone.html'),
        name="password_reset_complete",
    ),

]

online_shop/api/urls.py
from django.urls import path, include
from .views import *
urlpatterns = [
    path('laptop/list/', LaptopListAPIView.as_view()),
    path('mobile/list/', MobileListAPIView.as_view()),
    path('product/detail/<int:pk>/', ProductRetrieveUpdateDeleteAPIView.as_view()),

    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),

    path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/',
         PassResetConfirmView.as_view(),
         name='password_reset_confirm')
]

online_shop/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from accountapp import views
from api.views import PassResetConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store_app.urls')),
    path('api/', include('api.urls')),
    path('accountapp/', include('accountapp.urls')),




]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/store_app/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'store_app'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

    path('laptops/', views.LaptopListView.as_view(), name='laptop-view'),
    path('search/', views.SearchView.as_view(), name='search-view'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='detail-view'),
    path('purchases/', views.ShoppingListView.as_view(), name='purchases-view'),
    path('m/<int:pk>/', views.shopping_basket_minus, name='m-view'),
    path('p/<int:pk>/', views.shopping_basket_plus, name='p-view'),
    path('factor/', views.factor_view, name='factor'),
    path('bank/', TemplateView.as_view(template_name='store_app/bank.html'), name='bank'),
    path('uns/', TemplateView.as_view(template_name='store_app/unsuccess-result.html'), name='unsuccess'),
    path('success/', views.result_success_view, name='success'),
    path('mobiles/', views.MobileListView.as_view(), name='mobile-view'),
]

online_shop/store_app/models.py
from django.db import models
from accountapp.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField


class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='store_app')
    brand = models.ForeignKey(to='Brand', on_delete=models.CASCADE, related_name='brands')
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='categories')
    explanation = RichTextField()
    price = models.IntegerField()
    count = models.SmallIntegerField()
    available = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

    def buy(self, num):
        """
            Parameter:
                num => number of specific product that a user want to buy
            If count of product(in database) is greater than num, then count of product minus num
            If count of product is less than one it means the product isn't available anymore

        """
        if self.count >= int(num):
            self.count = self.count - int(num)

        if self.count < 1:
            self.available = False

    def count_minus(self):
        """
            If a specific product is available, then it can be reduced
            If the count of a specific product get zero, then turn available to False
        """
        if self.count > 0:
            self.count = self.count - 1
        if self.count == 0:
            self.available = False

    def count_add(self):
        # Increase number of specific product in database and turn available to True
        self.count = self.count + 1
        self.available = True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store_app:detail-view', kwargs={'pk': self.id})


class Brand(models.Model):
    title = models.CharField(max_length=12)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=12)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class ShoppingBasket(models.Model):
    buyer = models.ForeignKey(User, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE, related_name='products')
    count = models.PositiveSmallIntegerField(default=1)

    class Meta:
        ordering = ['buyer']

    def __str__(self):
        return self.product.title


class Comment(models.Model):
    STATUS_CHOICE = [
        ("publish", "Publish"),
        ("draft", "Draft")
    ]
    status = models.CharField(max_length=7, choices=STATUS_CHOICE, default='draft')
    product = models.ForeignKey(Product, models.CASCADE)
    user = models.ForeignKey(User, models.CASCADE)
    subject = models.CharField(max_length=25)
    message = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['created_at']

online_shop/store_app/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'message']

online_shop/store_app/views.py
from django.shortcuts import render
from .forms import CommentForm
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, ShoppingBasket, Comment
from django.shortcuts import redirect


class ProductListView(ListView):
    """
        Base class for product views
        On every page user will see 12 objects of products list
    """
    model = Product
    context_object_name = 'products'
    template_name = 'store_app/product-list.html'
    paginate_by = 12


class LaptopListView(ProductListView):
    """
        This class inherit from ProductListView class
        It returns laptop products descending
    """
    queryset = Product.objects.filter(category__slug__exact='laptop').order_by('-created_at')


class MobileListView(ProductListView):
    """
        This class inherit from ProductListView class
        It returns mobile products descending
    """
    queryset = Product.objects.filter(category__slug__exact='mobile').order_by('-created_at')


class SearchView(LaptopListView):
    """
        This page inherits from 'LaptopListView' class
        Get information about search box and return posts whose titles contain search box information
        Also, there is no pagination and all posts appear on one page
    """
    paginate_by = 0

    def get_queryset(self):
        search = self.request.GET.get('search')
        products = Product.objects.filter(title__icontains=search)
        return products


class ProductDetailView(DetailView):
    """
        Details about a particular product
        Logged in users can add product to their shopping basket and leave a comment about the product
    """
    model = Product
    context_object_name = 'product'
    template_name = 'store_app/products-detail.html'

    def get_context_data(self, **kwargs):
        """
            It returns comment form and published comments for specific product
        """
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm
        context['comments'] = Comment.objects.filter(product_id=self.kwargs['pk'], status__exact='publish')
        return context

    def post(self, request, **kwargs):
        """
            The user specifies the number of products and clicks on the 'Buy' button, the product will add to the user's
            shopping basket and the number of that product will be reduced from the database. If a product exists in
            the shopping basket and the user decide to click again on the buy button it will add to the number of
            that product in the user's shopping basket
        """
        if 'count' in request.POST:
            product = Product.objects.get(id=self.kwargs['pk'])
            number = request.POST.get('count')
            product.buy(number)
            product.save()
            if ShoppingBasket.objects.filter(product=product, buyer=request.user).exists():
                t = ShoppingBasket.objects.get(product=product)
                t.count = t.count + int(number)
                t.save()
            else:
                ShoppingBasket.objects.create(product=product, buyer=request.user, count=number)
            return redirect('store_app:purchases-view')

        if 'subject' in request.POST:
            # If user submit a comment, and if it was valid, it will save in database
            form = CommentForm(request.POST)
            if form.is_valid():
                subject = form.cleaned_data['subject']
                message = form.cleaned_data['message']
                user = request.user
                product = self.model.objects.get(id=self.kwargs['pk'])
                comment = Comment(product=product, user=user, subject=subject, message=message)
                comment.save()
            return redirect('store_app:detail-view', self.kwargs['pk'])


class ShoppingListView(LoginRequiredMixin, ListView):
    """
        For access to this view user must be logged in
        This class return user's purchases list
    """
    model = ShoppingBasket
    template_name = 'store_app/shopping-list.html'
    context_object_name = 'purchases'

    def get_queryset(self):
        return self.model.objects.filter(buyer=self.request.user)


def shopping_basket_minus(req, pk):
    """
        After a particular user added a product to her/him shopping basket, he/she can reduce or increase the number of
        that product on her/him shopping basket. When a user decides to reduce the number of specific products on
        her/him shopping basket, He / She click on the '-' link. After clicking on '-', this function will be called.
        This function reduces the number of that specific product in the shopping basket. Then the number of that
        specific product in the database will be increased.
        If a user has one specific product of products he/she will see 'delete' link instead of '-' link.After clicking
        on 'delete', the specific product will be removed from the shopping basket, and increase number of that product
        in the database
    """
    purchase = ShoppingBasket.objects.get(id=pk)
    current_product = Product.objects.get(id=purchase.product.id)
    if purchase.count > 1:
        purchase.count = purchase.count - 1
        purchase.save()

    else:
        purchase.delete()
    current_product.count_add()
    current_product.save()
    return redirect('store_app:purchases-view')


def shopping_basket_plus(req, pk):
    """
        After a particular user added a product to her/him shopping basket, he/she can reduce or increase the number of
        that product on her/him shopping basket. When a user decides to increase the number of specific products on
        her/him shopping basket, He / She click on the '+' link. After clicking on '+', this function will be called.
        This function increases the number of that specific product in the shopping basket. Then the number of that
        specific product in the database will be reduces.
    """
    purchase = ShoppingBasket.objects.get(id=pk)
    current_product = Product.objects.get(id=purchase.product.id)
    if current_product.count > 0:
        purchase.count = purchase.count + 1
        purchase.save()
        current_product.count_minus()
        current_product.save()
    return redirect('store_app:purchases-view')


def factor_view(req):
    """
        It returns specific user purchases and total price of shopping
    """
    purchases = ShoppingBasket.objects.filter(buyer=req.user)
    total = 0
    for purchase in purchases:
        total += purchase.product.price * purchase.count
    return render(req, 'store_app/factor.html', {'purchases': purchases, 'total_price': total})


def result_success_view(req):
    """
        If bank transaction being successful this function will call
        It deleted specific user shopping basket
    """
    purchases = ShoppingBasket.objects.filter(buyer=req.user)
    purchases.delete()
    return render(req, 'store_app/success-result.html')

online_shop/templates/store_app/bank.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}
<div class="container text-center">
    <a class="btn btn-danger" style="padding: 70px" href="{% url 'store_app:unsuccess' %}">Fail</a>
    <a class="btn btn-success" style="padding: 70px" href="{% url 'store_app:success' %}">Success</a>
</div>
{% endblock %}

online_shop/templates/store_app/factor.html
{% extends 'base.html' %}
{% load humanize %}


{% block head %}
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>
{% endblock head %}
    

{% block content %}
{% if not purchase %}
    <table class="table">
        <tr>
            <th>Product</th>
            <th>Count</th>
            <th>One Price</th>
            <th>Price</th>
        </tr>
        {% for purchase in purchases %}
        <tr>
            <td>{{ purchase.product.title }}</td>
            <td>{{ purchase.count }}</td>
            <td>{{ purchase.product.price|intcomma }} $</td>
            {% widthratio purchase.product.price 1 purchase.count as price %}
            <td>  {{ price|intcomma }} $</td>

        </tr>
        
        {% endfor %}
        <tr>
            {% comment %} <td></td><td></td><td></td> {% endcomment %}
            <th>total price: {{total_price|intcomma}} $</th>
        </tr> 
    </table>
    <div class="container text-center" style="margin: 20px">
        <a style="padding-left: 30px; padding-right: 30px;" class="btn btn-primary" href="{% url 'store_app:bank' %}">Pay</a>
    </div>{% else %}
    <h1> Your basket is empty </h1>
{% endif %}
{% endblock content %}

online_shop/templates/store_app/product-list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for product in products %}
        <div class="col">
            <div class="card text-center h-100">
                <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5>{{product.title}}</h5>
                    {% if product.available %}
                        <p>price: {{product.price|intcomma }} $</p>
                    {% else %}
                        <p style="color:red"> Not available </p>
                    {% endif %}
                    <a href="{% url 'store_app:detail-view' product.id %}" class="btn btn-primary">Buy</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if page_obj.has_other_pages %}
    <div class="container">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"  aria-disabled="true">Previous</a>
            </li>
            {% for page in page_obj.paginator.page_range %}
              <li class="{% if page_obj.number == page %} active {% endif %}page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
              <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">Next</a>
            </li>

          </ul>
        </nav>
    </div>
    {% endif %}

{% endblock %}

online_shop/templates/store_app/products-detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load django_bootstrap5 %}

{% block content %}

<div class="row">
    <div class="col-sm-3 ">
      <img src="{{ product.image.url }}" alt="" width="300" height="300">
    </div>
    <div class="col-sm-9">
        <br>
        <h3>{{ product.title}}</h3>
        <p style="margin-top: 40px">Price: {{ product.price|intcomma }} $</p>

        {% if user.is_authenticated %}
            {% if product.available %}
            <form method='post'>
                {% csrf_token %}
                <label style="margin-top: 40px"> Count: </label>
                <input type='number' value=1 name='count' min=1 max={{ product.count }}>
                <p style="margin-top: 40px"><input style="margin-top: 25px; padding-left:35px; padding-right:35px" type="submit" class="btn btn-primary" value="Buy"></p>
            </form>

            {% endif %}
            {% elif not product.available %}
             <h2 style="color:red;margin-top: 40px">Product Finished.</h2>
            {% else %}
            <p style="margin-top: 40px"> To purchase, please <a href="{% url 'accountapp:login-view' %}">login</a> </p>
        {% endif %}
    </div>
    <div class="container" style="margin-top: 25px;">
    <p>
        {{ product.explanation|safe }}
    </p>
    </div>

    {% if comments %}
        <div class="container" style="margin-top: 70px;">
            <div style="text-align: center">
                <h4>Comment Section</h4>
                <p>Number of comments: {{ comments.count }}</p>
            </div>
            <hr>
            {% for cm in comments %}
                <div class="">
                    <p style="font-family: Fantasy; text-indent: 30px">{{ cm.user.username }}</p>
                    <p style="font-weight: lighter; font-size: 12px; text-indent: 30px">{{ cm.created_at|date }} in {{ cm.created_at|time }}</p>
                    <p>{{ cm.message }}</p>
                </div>
                <hr>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container" style="margin-top: 70px;">
        <div style="text-align: center">
                <h5>Leave your comment</h5>
            </div>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="Send">
        </form>
    </div>
</div>

{% endblock %}

online_shop/templates/store_app/shopping-list.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}
{% if purchases %}
{% for purchase in purchases %}
    <div class="card">

        <div class="row no-gutters">

            <div class="col-auto">
                <img src="{{ purchase.product.image.url }}" width="170" class="img-fluid" alt="">
            </div>
            <div class="col">
                <div class="card-block px-2">
                    <h4 class="card-title">{{ purchase.product.title }}</h4>
                    <h5 class="card-text">Price: {{ purchase.product.price|intcomma }} $</h5>
                    <div class="number">
                        <span style="width:20px;height:20px;background:#f2f2f2;border-radius:4px;
                            padding:8px 5px 8px 5px;border:1px solid #ddd;text-align: center;"
                              class="minus"><a style="color:red;text-decoration: None" href="{% url 'store_app:m-view' purchase.id %}">{% if purchase.count == 1 %}delete {% else %}-{% endif %}</a></span>
                        <input style="border:1px solid #ddd;border-radius:4px;height:34px;width:50px;text-align: center" type="text" value="{{ purchase.count }}"/>
                        <span class="plus"style="width:20px;height:20px;background:#f2f2f2;border-radius:4px;
                            padding:8px 5px 8px 5px;border:1px solid #ddd;
                            text-align: center;"><a style="text-decoration: None" href="{% url 'store_app:p-view' purchase.id %}">+</a></span>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endfor %}
    <div class="container text-center" style="margin: 20px">
        <a style="padding-left: 30px; padding-right: 30px;" class="btn btn-primary" href="{% url 'store_app:factor' %}">Finish</a>
    </div>
{% else %}
    <h1 style="text-align: center; margin-bottom: 400px">Your shopping basket is empty.</h1>
{% endif %}
{% endblock %}

online_shop/templates/store_app/success-result.html
{% extends 'base.html' %}

{% block content %}

    <h1>Your payment was successfull.</h1>

{% endblock %}

online_shop/templates/store_app/unsuccess-result.html
{% extends 'base.html' %}


{% block content %}

    <h4> You're payment wasn't successful. <a href="{% url 'store_app:factor' %}"> please try again. </a></h4>

{% endblock %}